package TemperatureApp;


/**
* TemperatureApp/_TemperatureImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Temperature.idl
* 20 August 2021 14:54:56 o'clock IST
*/

public abstract class _TemperatureImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements TemperatureApp.Temperature, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _TemperatureImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("showTemperature", new java.lang.Integer (0));
    _methods.put ("setTemperature", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TemperatureApp/Temperature/showTemperature
       {
         String $result = null;
         $result = this.showTemperature ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // TemperatureApp/Temperature/setTemperature
       {
         String $result = null;
         $result = this.setTemperature ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TemperatureApp/Temperature:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _TemperatureImplBase
