package TemperatureApp;


/**
* TemperatureApp/TemperatureOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Temperature.idl
* 20 August 2021 14:54:56 o'clock IST
*/

public interface TemperatureOperations 
{
  String showTemperature ();
  String setTemperature ();
} // interface TemperatureOperations
