package TemperatureApp;

/**
* TemperatureApp/TemperatureHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Temperature.idl
* 20 August 2021 14:54:56 o'clock IST
*/

public final class TemperatureHolder implements org.omg.CORBA.portable.Streamable
{
  public TemperatureApp.Temperature value = null;

  public TemperatureHolder ()
  {
  }

  public TemperatureHolder (TemperatureApp.Temperature initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TemperatureApp.TemperatureHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TemperatureApp.TemperatureHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TemperatureApp.TemperatureHelper.type ();
  }

}
