package TemperatureApp;


/**
* TemperatureApp/Temperature.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Temperature.idl
* 20 August 2021 14:54:56 o'clock IST
*/

public interface Temperature extends TemperatureOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Temperature
